# Generated by Django 4.2.6 on 2023-10-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staking_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userposition",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="stackingpool",
            name="stack_holders",
            field=models.ManyToManyField(
                blank=True, related_name="stacking_pools", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="poolconditions",
            name="pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="staking_app.stackingpool",
            ),
        ),
    ]
