# Generated by Django 4.2.6 on 2023-10-26 17:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staking_app", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StackingPool",
            new_name="StakingPool",
        ),
    ]
