# Generated by Django 4.2.6 on 2023-10-26 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staking_app", "0003_rename_stackingpool_stakingpool"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stakingpool",
            old_name="stack_holders",
            new_name="stak_holders",
        ),
    ]
